require("configs.options")
require("configs.keymaps")
require("configs.autocmds")
-- require("plugins.statusline")
require("plugins.sl")
require("plugins.lsp")
require("plugins.utils")
require("plugins.colorscheme")
require("plugins.edit")
require("plugins.floatterm")
require("plugins.task")
require("plugins.animate")
